services:
  - type: web
    name: fastapi-app
    runtime: python
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /opt/render/project/.cache
